server:
  port: 8081
spring:
  application:
    name: trip-planner-service
services:
  location:
    base-url: ${LOCATION_SERVICE_URL:http://localhost:8082}
  weather:
    base-url: ${WEATHER_SERVICE_URL:http://localhost:8083}
  currency:
    base-url: ${CURRENCY_SERVICE_URL:http://localhost:8084}
management:
  endpoints:
    web:
      exposure:
        include: health,info
